version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Update dependencies"