#version: 2
#updates:
#  - package-ecosystem: "gomod"
#    directory: "/"
#    schedule:
#      interval: "daily"
#      timezone: "Asia/Tokyo"
#
#  - package-ecosystem: "docker"
#    directory: "/"
#    schedule:
#      interval: "daily"
#      timezone: "Asia/Tokyo"