version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "Docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "Asia/Tokyo"