version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:40"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:40"
      timezone: "Asia/Tokyo"