version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: lab-db
    ports:
    - "3306:3306"
    volumes:
    - ./docker/mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "questionnaire"
      TZ: "Asia/Tokyo"